// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC732p1h58cmEvKGC7cznY3I23_mAmrXBg',
    appId: '1:479750710585:web:b637db9fa439677ba9b4e8',
    messagingSenderId: '479750710585',
    projectId: 'fluttermlkitgdc22',
    authDomain: 'fluttermlkitgdc22.firebaseapp.com',
    storageBucket: 'fluttermlkitgdc22.appspot.com',
    measurementId: 'G-VF4R01Y458',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEPwfAhwFjEFOXjZSaxNd_XGJ9r_G0QY0',
    appId: '1:479750710585:android:66021be2d2e2b3d6a9b4e8',
    messagingSenderId: '479750710585',
    projectId: 'fluttermlkitgdc22',
    storageBucket: 'fluttermlkitgdc22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlLMDIe3ZJub5U1EiYboL1mAjt9uVP4tA',
    appId: '1:479750710585:ios:b0ee1df2e119f84ba9b4e8',
    messagingSenderId: '479750710585',
    projectId: 'fluttermlkitgdc22',
    storageBucket: 'fluttermlkitgdc22.appspot.com',
    iosClientId: '479750710585-gr36tddqt5th66mp3qmdo52nsobc46hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mlflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlLMDIe3ZJub5U1EiYboL1mAjt9uVP4tA',
    appId: '1:479750710585:ios:b0ee1df2e119f84ba9b4e8',
    messagingSenderId: '479750710585',
    projectId: 'fluttermlkitgdc22',
    storageBucket: 'fluttermlkitgdc22.appspot.com',
    iosClientId: '479750710585-gr36tddqt5th66mp3qmdo52nsobc46hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mlflutter',
  );
}
